language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python3.6 -m pytest tests/
  - coverage run --source ProFootballRef -m py.test
after_success:
  - coveralls

